=== pkumarex/intel-secl/pkg/hvs/domain/schema/flavor-template.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://intel.com/intel-secl/schemas/flavor_template.schema.json",
    "title": "flavor_template",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "label": {
            "$ref": "common.schema.json#/definitions/non_empty_string"
        },
        "condition": {
            "description": "An array of 'jsonquery' statements that are used to determine if the template should be executed.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minLength": 1
        },
        "flavor_parts": {
            "$ref": "#/definitions/flavor_template_map"
        }
    },
    "additionalItems": false,
    "required": [
        "label",
        "condition",
        "flavor_parts"
    ],
    "definitions": {
        "flavor_template_map": {
            "description": "A map of flavor_part name strings to the flavor_template objects",
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/flavor_template"
            }
        },
        "flavor_template": {
            "type": "object",
            "properties": {
                "meta": {
                    "description": "Arbitrary key/value pairs of meta data that will be copied to the flavor's meta/description object.",
                    "type": "object"
                },
                "pcr_rules": {
                    "description": "An array of verification rules that will be applied to a PCR.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pcr_rule"
                    },
                    "minItems": 1
                }
            },
            "additionalItems": false,
            "required": [
                "meta",
                "pcr_rules"
            ]
        },
        "pcr_rule": {
            "properties": {
                "pcr": {
                    "description": "The index and bank of the PCR to verify.",
                    "$ref": "common.schema.json#/definitions/pcr"
                },
                "pcr_matches": {
                    "type": "boolean"
                },
                "eventlog_equals": {
                    "description": "Identifies which events in a PCR index/bank to copy to the resulting flavor to enforce the 'PCR Event Includes' verification.",
                    "properties": {
                        "excluding_tags": {
                            "description": "A list of event tags to ignore when comparing the logs for equality.",
                            "$ref": "common.schema.json#/definitions/eventlog_tags"
                        }
                    }
                },
                "eventlog_includes": {
                    "description": "Identifies which event tags in a PCR index/bank to copy to the resulting flavor to enforce a 'PCR Event Equals' verification.",
                    "$ref": "common.schema.json#/definitions/eventlog_tags"
                }
            },
            "additionalProperties": false,
            "required": [
                "pcr"
            ],
            "not": {
                "description": "Don't allow the 'eventlog_equals' and 'eventlog_includes' in the same pcr index/bank.",
                "required": [
                    "eventlog_equals",
                    "eventlog_includes"
                ]
            }
        }
    }
}

=== pkumarex/intel-secl/tools/flavor-convert/flavortemplates/linux_tpm20_tboot.template.json
{
	"id": "ab2a4f35-6d6e-4fd3-bcb8-1ae57576e3c7",
	"label": "linux-tpm20-tboot",
	"condition": [
		"//host_info/vendor//*[text()='Linux']",
		"//host_info/tpm_version//*[text()='2.0']",
		"//host_info/tboot_installed//*[text()='true']"
	],
	"flavor_parts": {
		"PLATFORM": {
			"meta": {
				"bios_name": "{{//host_info/bios_name}}",
				"bios_version": "{{//host_info/bios_version}}",
				"tpm_version": "2.0",
				"tboot_installed": true
			},
			"pcr_rules": [
				{
					"pcr": {
						"index": 17,
						"bank": "SHA256"
					},
					"pcr_matches": true,
					"eventlog_equals": {
						"excluding_tags": [
							"LCP_CONTROL_HASH",
							"initrd",
							"vmlinuz"
						]
					}
				},
				{
					"pcr": {
						"index": 18,
						"bank": "SHA256"
					},
					"pcr_matches": true,
					"eventlog_equals": {
						"excluding_tags": [
							"LCP_CONTROL_HASH",
							"initrd",
							"vmlinuz"
						]
					}
				}
			]
		},
		"OS": {
			"meta": {
				"os_name": "{{//host_info/meta/description/os_name}}",
				"os_version": "{{//host_info/ meta/description/os_version}}",
				"tpm_version": "2.0",
				"tboot_installed": true
			},
			"pcr_rules": [
				{
					"pcr": {
						"index": 17,
						"bank": "SHA256"
					},
					"pcr_matches": true,
					"eventlog_includes": [
						"vmlinuz"
					]
				}
			]
		},
		"HOST_UNIQUE": {
			"meta": {
				"os_name": "{{//host_info/meta/description/os_name}}",
				"os_version": "{{//host_info/ meta/description/os_version}}",
				"tpm_version": "2.0",
				"tboot_installed": true
			},
			"pcr_rules": [
				{
					"pcr": {
						"index": 17,
						"bank": "SHA256"
					},
					"pcr_matches": true,
					"eventlog_includes": [
						"LCP_CONTROL_HASH",
						"initrd"
					]
				},
				{
					"pcr": {
						"index": 18,
						"bank": "SHA256"
					},
					"pcr_matches": true,
					"eventlog_includes": [
						"LCP_CONTROL_HASH"
					]
				}
			]
		}
	}
}

=== pkumarex/intel-secl/pkg/lib/flavor/test/resources/TestTemplate.json
{
    "id": "fe20cb78-4584-4635-a674-e9af2a9e5f76",
    "label": "test-template",
    "condition": [
        "//host_info/tpm_enabled='true'",
        "//host_info/tpm_version='2.0'",
        "//host_info/txt_enabled='true'"
    ],
    "flavor_parts": {
        "PLATFORM": {
            "meta": {
                "tboot_installed": true,
                "tpm_version": "2.0"
            },
            "pcr_rules": [
                {
                    "pcr": {
                        "index": 0,
                        "bank": "SHA256"
                    },
                    "pcr_matches": true
                },
                {
                    "pcr": {
                        "index": 17,
                        "bank": "SHA256"
                    },
                    "pcr_matches": true,
                    "eventlog_equals": {
                        "excluding_tags": [
                            "LCP_CONTROL_HASH",
                            "initrd",
                            "vmlinuz"
                        ]
                    }
                },
                {
                    "pcr": {
                        "index": 18,
                        "bank": "SHA256"
                    },
                    "pcr_matches": true,
                    "eventlog_equals": {
                        "excluding_tags": [
                            "LCP_CONTROL_HASH",
                            "initrd",
                            "vmlinuz"
                        ]
                    }
                }
            ]
        }
    }
}

=== pkumarex/intel-secl/tools/flavor-convert/flavortemplates/linux_tpm20_cbnt.template.json
{
    "id": "f7e3ee4c-944b-4030-9d32-94d22773573d",
    "label": "linux-tpm20-cbnt",
    "condition": [
		"//host_info/vendor//*[text()='Linux']",
        "//host_info/tpm_version//*[text()='2.0']",
        "//host_info/hardware_features/cbnt/enabled//*[text()='true']"
    ],
    "flavor_parts": {
        "PLATFORM": {
            "meta": {
                "tpm_version": "2.0",
                "cbnt_enabled": true
            },
            "pcr_rules": [
                {
                    "pcr": {
                        "index": 7,
                        "bank": "SHA256"
                    },
                    "pcr_matches": true
                }
            ]
        }
    }
}
